name: build-test-deploy
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build
