name: hello-world
on:
#  workflow_dispatch: 
  schedule:
    - cron: "*/2 * * * *"


jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - run: echo "{cat hello_world.txt}"
      - run: cat hello_world.txt
    
